version: '3'
services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

  celery:
    image: python:3.10
    container_name: celery-worker
    command: bash -c "pip install -r requirements.txt && celery -A celery_app worker --loglevel=info"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis

