version: '3'
services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

  celery:
    image: python:3.10
    container_name: celery-worker
    command: bash -c "pip install -r requirements.txt && celery -A celery_app.app worker --loglevel=info"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    env_file:
      - .env

  main:
    image: python:3.10
    container_name: main-app
    command: bash -c "pip install -r requirements.txt && python main.py"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
      - celery
    env_file:
      - .env


